version: '3.7'

services:
  ts-node-docker:
    container_name: doxerjs-dev
    build:
      target: base
    environment:
      - NODE_ENV=dev
      - APP_ENV=DEV
    command: npm run start
